mydjpro/Scripts/mysite/account/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'account'

urlpatterns = [
    # path('login/', views.user_login, name='user_login'),
    path('login/', auth_views.LoginView.as_view(template_name='account/login2.html'), name='user_login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='account/logout.html'), name='user_logout'),
    path('register/', views.register, name='user_register'),

    path('password-change/', auth_views.PasswordChangeView.as_view(template_name='account/password_change_form.html',
                                                                   success_url='/account/password-change-done/'), name='password_change'),
    path('password-change-done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='account/password_change_done.html'),
         name='password_change_done'),

    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='account/password_reset_form.html',
                                                                 email_template_name='account/password_reset_email.html',
                                                                 subject_template_name='account/password_reset_subject.txt',
                                                                 success_url='/account/password-reset-done/'),
         name='password_reset'),

    path('password-reset-done/',
         auth_views.PasswordResetDoneView.as_view(template_name='account/password_reset_done.html'),
         name='password_reset_done'),

    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='account/password_reset_confirm.html',
                                                     success_url='/account/password-reset-complete/'),
         name='password_reset_confirm'),

    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='account/password_reset_complete.html'),
         name='password_reset_complete'),

    path('aboutme/', views.myself, name='aboutme'),

    path('editme/', views.myself_edit, name='editme'),
]

mydjpro/Scripts/mysite/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.blog_title, name='blog_title'),
    path('<int:article_id>/', views.blog_article, name='blog_article'),
]

mydjpro/Scripts/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('account/', include('account.urls', namespace='account')),
]

mydjpro/Scripts/mysite/templates/base.html
{% load staticfiles %}
<!DOTYPE html>
<html lang='zh-cn'>
    <head>
        <meta charset='utf-8'>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
        <title>{% block title %}{% endblock %}</title>
    </head>
    <body>
        {% include 'header.html' %}
        <div class='container'>
            {% block content %}
            {% endblock %}
        </div>
        {% include 'footer.html' %}
        {% block javascript %}{% endblock %}
    </body>
</html>

mydjpro/Scripts/mysite/templates/footer.html
<div class='container'>
    <hr>
    <p class='text-center'>XF微专业：Python全栈工程师</p>
</div>

mydjpro/Scripts/mysite/templates/header.html
{% load staticfiles %}
<div class='container'>
    <nav class='navbar navbar-default' rol='navigation'>
        <div class='navbar-header'>
            <img src="{% static './images/logo.png'%}" width=100>
        </div>
        <div>
            <ul class='nav navbar-nav'>
                <li><a href="{% url 'blog:blog_title' %}">BLOG</a></li>
            </ul>
            <ul class='nav navbar-nav navbar-right'>
                {% if user.is_authenticated %}
                <li><!--start modify: dropdown menu of password change-->
                    <div class='dropdown'>
                        <button class='btn btn-default dropdown-toggle' type='button' id='dropdownMenu' data-toggle='dropdown'>{{ user.username }}<span class='caret'></span></button>
                        <ul class='dropdown-menu'>
                            <li><a href="{% url 'account:password_change' %}">修改密码</a></li>
                            <li><a href="{% url 'account:aboutme' %}">个人信息</a></li>
                        </ul>
                    </div>
                </li><!--end-->
                <li><a href="{% url 'account:user_logout' %}">退出</a></li>
                {% else %}
                <li><a href="{% url 'account:user_login' %}">登录</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
</div>

<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/bootstrap.js' %}"></script>